[package]
name = "cracking-code-rs"
version = "0.1.0"
authors = ["Ravi Sankar Karuturi <ravi.sankar.karuturi@macys.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
